"""
This is a setup.py script generated by py2applet
Usage: python setup.py py2app
"""
import re
from setuptools import setup

# Dynamically extract the version from main.py
with open('main.py', 'r') as f:
    version_string = re.search(r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]', f.read(), re.MULTILINE).group(1)

APP = ['main.py']
DATA_FILES = []

OPTIONS = {
    'iconfile': 'icons/app_icon.icns', 
    'argv_emulation': True,              
    'frameworks': ['/opt/homebrew/Caskroom/miniconda/base/envs/nmrdraw-lite-intel/lib/libffi.8.dylib'],
    'plist': {
        'CFBundleName': 'NMRdraw_lite',
        'CFBundleShortVersionString': version_string, 
        'CFBundleVersion': version_string,            
    }
}

setup(
    app=APP,
    version=version_string, 
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
